const {chromium}=require(process.env.PERFCHECKER_PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.PERFCHECKER_BROWSER?{executablePath:process.env.PERFCHECKER_BROWSER}:{})});
  const page=await browser.newPage({viewport:{width:1250,height:1000}}),errors=[];
  page.on('pageerror',error=>errors.push(String(error)));
  const state={type:'chatState',workspace:'Julia demo',messages:[],evidence:[{id:'safe',label:'Saved evidence'},
    {id:'suite:workspace-run',label:'Suite · saved measured run'},
    {id:'suite-unavailable:workspace',label:'Suite evidence unavailable · Missing integrity',unavailable:true}],
    evidenceId:'',pending:'',busy:false,status:'Ready',implementation:{tool:'implement',promptArgument:'prompt',workspaceArgument:'workspace'}};
  try {
    await page.setContent('<!doctype html><html lang="en"><body><main id="chat-root"></main></body></html>');
    await page.addStyleTag({path:path.join(__dirname,'../media/advisor-chat.css')});
    await page.addScriptTag({path:path.join(__dirname,'../media/advisor-chat.js')});
    await page.evaluate(()=>{globalThis.requests=[];globalThis.panel=mountAdvisorChat(document.getElementById('chat-root'),message=>requests.push(message));});
    await page.evaluate(value=>panel.receive(value),state);
    assert.equal((await page.evaluate(()=>requests)).length,0);
    assert.equal(await page.locator('select[aria-label="Attach saved evidence"] option[value="suite-unavailable:workspace"]').evaluate(option=>option.disabled),true);
    await page.getByRole('combobox',{name:'Attach saved evidence',exact:true}).selectOption('suite:workspace-run');
    assert.deepEqual(await page.evaluate(()=>requests.at(-1)),{type:'chatClear',evidenceId:'suite:workspace-run'});
    state.evidenceId='suite:workspace-run';
    await page.locator('summary').filter({hasText:'Optional Codex CLI connector'}).click();
    await page.getByRole('button',{name:'Connect Codex CLI',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatConnectCodex');
    state.connection='codex-cli 0.159.2 · local connector';await page.evaluate(value=>panel.receive(value),state);
    assert.ok(await page.getByRole('button',{name:'Connect Codex CLI',exact:true}).isHidden());
    await page.getByRole('button',{name:'Disconnect Codex',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatDisconnectCodex');
    delete state.connection;await page.evaluate(value=>panel.receive(value),state);
    await page.getByRole('textbox',{name:'Ask about configuration'}).fill('How can I reduce allocations?');
    await page.getByRole('textbox',{name:'Ask about configuration'}).press('Control+Enter');
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatSend');
    assert.equal((await page.evaluate(()=>requests.at(-1))).evidenceId,'suite:workspace-run');
    assert.ok(await page.getByRole('button',{name:'Send question',exact:true}).isDisabled());
    await page.getByRole('button',{name:'Cancel request',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatCancel');
    state.messages=[{role:'user',content:'How can I reduce allocations?'},{role:'assistant',content:'<script>globalThis.injected=true</script>\nPreserve correctness.'}];
    await page.evaluate(value=>panel.receive(value),state);
    assert.equal(await page.evaluate(()=>globalThis.injected),undefined); assert.equal(await page.locator('#chat-root script').count(),0);
    assert.equal(await page.getByRole('textbox',{name:'Ask about configuration'}).inputValue(),'');
    await page.getByRole('tab',{name:'01 · Advice',exact:true}).focus();
    await page.getByRole('tab',{name:'01 · Advice',exact:true}).press('ArrowRight');
    assert.equal(await page.getByRole('tab',{name:'02 · Implementation',exact:true}).getAttribute('aria-selected'),'true');
    assert.ok(await page.getByRole('textbox',{name:'Ask about configuration'}).isHidden());
    await page.getByText('Latest advice to implement',{exact:true}).click();
    assert.ok(await page.locator('#chat-implementation').getByText('Preserve correctness.',{exact:false}).isVisible());
    const before=(await page.evaluate(()=>requests)).length;
    await page.getByRole('button',{name:'I reviewed the advice · Prepare implementation',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatImplement');
    assert.equal((await page.evaluate(()=>requests)).length,before+1);
    assert.ok(await page.locator('.proposal').isHidden());
    state.proposal={patch:'diff --git a/x.jl b/x.jl\n- old\n+ new <img onerror="globalThis.injected=true">',files:['x.jl'],applied:false}; state.backupRef='refs/perfchecker/checkpoints/test';
    state.implementationSummary='Prepared changes. <script>still plain text</script>';
    await page.evaluate(value=>panel.receive(value),state);
    await page.getByRole('button',{name:'Apply reviewed changes',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatApply');
    state.proposal.applied=true; await page.evaluate(value=>panel.receive(value),state);
    await page.getByRole('button',{name:'Restore previous code',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).type,'chatRestore');
    await page.evaluate(value=>panel.receive(value),state);
    await page.getByText('Configure the MCP implementation tool',{exact:true}).click();
    await page.getByRole('textbox',{name:'Implementation tool name',exact:true}).fill('implement_code');
    await page.getByRole('button',{name:'Save implementation tool',exact:true}).click();
    assert.equal((await page.evaluate(()=>requests.at(-1))).tool,'implement_code');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.deepEqual(errors,[]); assert.equal(await page.evaluate(()=>globalThis.injected),undefined);
    console.log('Chat browser checks passed: explicit requests, keyboard tabs, cancellation, text escaping, diff review, apply/restore, configuration and mobile width.');
  } finally {await browser.close();}
})();
